version: "2"

services:
  voting-app:
    #build: ./voting-app
    image: $DTR/$REPO/voting-app:$GIT_COMMIT
    volumes:
     - ./voting-app:/app
    ports:
      - "80:80"
    restart: always
    networks:
      - front-tier
      - back-tier

  result-app:
    #build: ./result-app
    image: $DTR/$REPO/result-app:$GIT_COMMIT
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    #build: ./worker
    image: $DTR/$REPO/worker:$GIT_COMMIT
    networks:
      - back-tier

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
volumes:
  db-data:

networks:
  front-tier:
  back-tier:
